config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  get 'users/new'
  get 'activations/new'

  root :to => 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/activations', to: 'activations#new'
  post '/activations', to: 'activations#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :activations
  
end

app/models/activation.rb
class Activation < ApplicationRecord
  validates :dealer_store, presence: true, length: { maximum: 50 }
  validates :customer_name, presence: true, length: { maximum: 50 }
  validates :device_id, presence: true, length: { maximum: 20 }
  validates :activation_code, presence: true, length: { maximum: 20 }
  validates :zip_code, presence: true, length: { maximum: 5 }
  validates :area_code, presence: true, length: { maximum: 3 }
  #validates :number_to_port_in, presence: true, length: { maximum: 10 }
  #validates :account_number, presence: true, length: { maximum: 20 }
  #validates :account_passcode, presence: true, length: { maximum: 10 }
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  validates :phone_number, presence: true, length: { maximum: 10 }
  validates :dealer_store, presence: true, length: { maximum: 255 }
end

app/controllers/activations_controller.rb
class ActivationsController < ApplicationController
  
  def show
    @activation = Activation.find(params[:id])
  end
  def new
    @activation = Activation.new
  end
  def create
    @activation = Activation.new(activation_params)
    if @activation.save
      redirect_to @activation
    else
      render 'new'
    end
  end
  
  private
  
  def activation_params
    params.require(:activation).permit(:dealer_store, :customer_name, :device_id, :activation_code, :zip_code, :area_code)
    
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :phone_number, :dealer_store)
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
# Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
 # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/activations/new.html.erb
<%= provide(:title, 'New Activations') %>
<h1>New Activations</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@activation, url: activations_path) do |f| %>
    <%= render 'shared/activation_error_messages' %>
    
      <%= f.label :dealer_store %>
      <%= f.text_field :dealer_store, class: 'form-control' %>
      
      <%= f.label :customer_name %>
      <%= f.text_field :customer_name, class: 'form-control' %>

      <%= f.label :device_id %>
      <%= f.text_field :device_id, class: 'form-control' %>
      
      <%= f.label :activation_code %>
      <%= f.text_field :activation_code, class: 'form-control' %>

      <%= f.label :zip_code %>
      <%= f.text_field :zip_code, class: 'form-control' %>

      <%= f.label :area_code %>
      <%= f.text_field :area_code, class: 'form-control' %>
      
      

      <%= f.submit "Submit Activation", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/activations/portin.html.erb
<%= provide(:title, 'New Activations') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    
      <%= f.label :dealer_store %>
      <%= f.text_field :dealer_store %>
      
      <%= f.label :customer_name %>
      <%= f.text_field :customer_name %>

      <%= f.label :device_id %>
      <%= f.text_field :device_id %>
      
      <%= f.label :activation_code %>
      <%= f.text_field :activation_code %>

      <%= f.label :zip_code %>
      <%= f.text_field :zip_code %>

      <%= f.label :area_code %>
      <%= f.text_field :area_code %>
      
      <%= f.label :number_to_port_in %>
      <%= f.telephone_field :number_to_port_in %>
      
      <%= f.label :account_number %>
      <%= f.text_field :account_number %>
      
      <%= f.label :account_passcode %>
      <%= f.text_field :account_passcode %>

      <%= f.submit "Submit Activation", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/activations/show.html.erb
<% provide(:title, @activation.dealer_store) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <p>Dealer Store: <%= @activation.dealer_store %></p>
        <p>Customer Name: <%= @activation.customer_name %></p> 
        <p>Device ID: <%= @activation.device_id %></p> 
        <p>Activation Code: <%= @activation.activation_code %></p>
        <p>Zip Code: <%= @activation.zip_code %></p>
        <p>Area Code: <%= @activation.area_code %></p>
      </h1>
    </section>
  </aside>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Kimani Embden</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Activations <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
               <li><%= link_to "New Activations", activations_path %></li>
               <li><%= link_to "Port-in Activations", '#' %></li>
               
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %> | Ruby on Rails Tutorial Sample App</title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
       <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_activation_error_messages.html.erb
<% if @activation.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@activation.errors.count, "error") %>.
      </div>
      <ul>
        <% @activation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
   </div>
 <% end %>
 

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
   </div>
 <% end %>
 

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails Tutorial</em></a> is a <a href="http://www.ralstutorial.org/book">book</a> and <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development wth <a href="http://rubyonrails.org/">Ruby on Rails</a>
This is the sample application for the tutorial.
</p>
</body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/contact">contact page</a>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help pages</a>.
  To get help on ths sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>book</a>
</p>

app/views/static_pages/home.html.erb
<!DOCTYPE HTML>
<div class="center jumbotron">
<h1>Sample App</h1>

<h2>


  This is the home page for the
  <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
</h2>
<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
    <%= render 'shared/error_messages' %>
    
      <%= f.label :dealer_store %>
      <%= f.text_field :dealer_store, class: 'form-control' %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>